### ISSUE TITLE
When I compile this project, I was prompted that “the helpers.hpp file is missing”

### ISSUE THREAD

**Issue by PiBigStar5712** [dhruvms/amra#1]
I tried to transfer this project to python and used some tools in the process. When using the tool to transfer, as shown in the title, I was told that the helpers.hpp file was missing. Is this file supposed to appear in this project? If so, how do I get this file? How should I place it? I look forward to your answer.

**Comment by dhruvms** [comment]
I can't comment on what went wrong trying to convert the project to Python, but the "missing" file can be found [here](https://github.com/dhruvms/amra/blob/master/include/amra/helpers.hpp) in the repository.
