### ISSUE TITLE
I would like to restart running this code and seek your help

### ISSUE THREAD

**Issue by XuYingTing1** [dhruvms/amra#4]
Due to running this code for too long, my thoughts have become a bit confused. I want to start running again now. I will describe my steps to you. First, I created a new workspace called "demo03_ws", then entered the workspace called "demo03_ws" and ran "git clone" on the terminal https://github.com/dhruvms/amra.git ”Then run 'cd amra&&mkdir build&&cd build&&cmake../&make - j ` nproc `' again, and I have already downloaded eigen-3.4.0 and boost_ 1_ 82_ 0. May I ask if I should do some social work next？I hope you can provide me with some help, thank you!

**Comment by dhruvms** [comment]
What you described only builds the codebase. To use it, you need to run one of the executables as explained in the "Running experiments" section of the readme. For example, from the `build` directory, you can execute `./run2d ../dat/Cauldron.map` to test AMRA* in a 2D gridworld map (Cauldron) from the MovingAI dataset
